name: RAD
main: com.simplyian.mc.rad.RAD
authors:
  - AlbireoX
description: Makes radiated areas.
version: 0.1
commands:
  rad:
    description: Makes a RAD zone.
    usage: /rad <zonename> [pos1|pos2]